
services:
  db:
    container_name: association_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: association_user
      POSTGRES_PASSWORD: association_password
      POSTGRES_DB: association_db
      
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data_association

volumes:
  db-data: {}



